### ISSUE TITLE
FrontEnd Initial Design

### ISSUE THREAD

**Issue by kelvinf96** [kelvinf96/PasswordManagerClientApp#1]
@RhysMcCabe 

Just push a skeleton of an app to the repo, I used VS Code to write the code as Android Studio wasn't working great for me on Mac. You should be able to use Android Studio for it with no issues though once you install the Flutter plugin for Android Studio. If you have an Q's regarding installing Flutter and getting is set up let me know ill help you out!

The device i'm using for the emulator is a 'Pixel 5 API 30' might be good if we use the same device for now while designing it out. Heres some screenshots of what I have done so far, let me know what you think and any recommendations you have for changes so far!

Home screen of app once the user opens it
<img width="1680" alt="Screenshot 2023-04-15 at 11 40 43" src="https://user-images.githubusercontent.com/53425707/232209381-4a5c0147-e2ee-4a90-9bcc-21581cdd5ba7.png">

Once User enters their number they are brought to their User Home Page, of course we will have endpoints here checking for existing accounts or creating a new one etc
<img width="1680" alt="Screenshot 2023-04-15 at 11 41 11" src="https://user-images.githubusercontent.com/53425707/232209420-20996b82-5bdd-4b9f-9749-832b05a625fb.png">

Finally I just added a small bit to the Account Settings page to show both the users phone number and android device ID being passed through the application.
<img width="1680" alt="Screenshot 2023-04-15 at 11 41 18" src="https://user-images.githubusercontent.com/53425707/232209456-17e11ebb-e5eb-4e84-b80d-6249253c0d19.png">

**Comment by RhysMcCabe** [comment]
Man fair play 👏 ! Looks great ! Will pull soon. I will gladly avoid android studio if I can 😅

**Comment by kelvinf96** [comment]
Yeah its well worth giving VS Code a shot if you can get it up and running, any issues you come across setting up flutter and the emulator in VS Code let me know and i'll try get it sorted for you! I think ive seen every flutter related error at this rate 😆
